name: Send email

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # REPOSITORY_URL: docker.pkg.github.com
      IMAGE_NAME: ${{ github.repository }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          # channel: '#workflows'
        if: always()
      - name: Checkout
        uses: actions/checkout@v2
      - name: Variables
        id: vars
        run: echo "::set-output name=SHORT_COMMIT_ID::$(git rev-parse --short HEAD)"
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
            # channel: '#workflows'
          message: 'hihi?'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}

        if: always()
